web:
  restart: always
  build: ./web
  expose:
    - "5000"
    - "9090"
    - "9091"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app
  env_file: .env
  command: uwsgi --http :5000 --wsgi-file app.py --callable app --processes 2 --threads 4
  #command: python app.py

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

#data:
#  restart: always
#  image: postgres:latest
#  volumes:
#    - /var/lib/postgresql
#  command: true

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql:data
  ports:
    - "5432:5432"
